mode: 'train'
exp_name: 'exp'
dataset: 'Clotho'
text_encoder: 'bert'
joint_embed: 1024
config: settings
train_sample: False
train_sample_ratio: 0.2

test_sample: True
test_sample_ratio: 0.3
wav:
  sr: 32000 
  window_size: 1024
  hop_length: 320
  mel_bins: 64

bert_encoder:
  type: 'bert-base-uncased'
  freeze: Yes

cnn_encoder:
  model: 'ResNet38'
  pretrained: Yes
  freeze: Yes

data:
  batch_size: 64
  num_workers: 8

training:
  margin: 0.2
  freeze: Yes
  loss: ntxent  # 'triplet', 'weight', 'ntxent'
  spec_augmentation: Yes
  epochs: 50
  lr: !!float 1e-4
  clip_grad: 2
#  seed: 20
  seed: 20
  resume: No
  l2_norm: Yes
  dropout: 0.2

path:
  vocabulary: 'data/{}/pickles/words_list_aug_0.4.p'
  word2vec: 'pretrained_models/w2v_all_vocabulary.model'
  resume_model: ''
